# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNowModel',
            fields=(
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('checked', models.DateTimeField(null=True, blank=True))
            ),
            options={
                'abstract': False,
            }
        )
    ]
