# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0002_auto_now_model')
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS appschema",
            reverse_sql="DROP SCHEMA IF EXISTS appschema"
        ),
        migrations.CreateModel(
            name='TestModelWithSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField(null=True, blank=True)),
                ('name', models.CharField(max_length=50, null=True, blank=True))
            ],
            options={
                'abstract': False,
                'db_table': '"appschema"."testmodel"'
            }
        ),
        migrations.AlterUniqueTogether(name='TestModelWithSchema', unique_together=[('id', 'name')]),
    ]
